//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EagleEye.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EagleEyeEntities : DbContext
    {
        public EagleEyeEntities()
            : base("name=EagleEyeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_account> tbl_account { get; set; }
        public virtual DbSet<tbl_att_status> tbl_att_status { get; set; }
        public virtual DbSet<tbl_attendence> tbl_attendence { get; set; }
        public virtual DbSet<tbl_awaitingdevice> tbl_awaitingdevice { get; set; }
        public virtual DbSet<tbl_communication> tbl_communication { get; set; }
        public virtual DbSet<tbl_department> tbl_department { get; set; }
        public virtual DbSet<tbl_designation> tbl_designation { get; set; }
        public virtual DbSet<tbl_device> tbl_device { get; set; }
        public virtual DbSet<tbl_employee> tbl_employee { get; set; }
        public virtual DbSet<tbl_employeetype> tbl_employeetype { get; set; }
        public virtual DbSet<tbl_exceptionlog> tbl_exceptionlog { get; set; }
        public virtual DbSet<tbl_expiredusers> tbl_expiredusers { get; set; }
        public virtual DbSet<tbl_fkcmd_trans> tbl_fkcmd_trans { get; set; }
        public virtual DbSet<tbl_fkcmd_trans_cmd_param> tbl_fkcmd_trans_cmd_param { get; set; }
        public virtual DbSet<tbl_fkcmd_trans_cmd_param_offline> tbl_fkcmd_trans_cmd_param_offline { get; set; }
        public virtual DbSet<tbl_fkcmd_trans_cmd_result> tbl_fkcmd_trans_cmd_result { get; set; }
        public virtual DbSet<tbl_fkcmd_trans_cmd_result_user_id_list> tbl_fkcmd_trans_cmd_result_user_id_list { get; set; }
        public virtual DbSet<tbl_fkcmd_trans_offline> tbl_fkcmd_trans_offline { get; set; }
        public virtual DbSet<tbl_fkdevice_status> tbl_fkdevice_status { get; set; }
        public virtual DbSet<tbl_irregularemployee> tbl_irregularemployee { get; set; }
        public virtual DbSet<tbl_location> tbl_location { get; set; }
        public virtual DbSet<tbl_menu> tbl_menu { get; set; }
        public virtual DbSet<tbl_menurights> tbl_menurights { get; set; }
        public virtual DbSet<tbl_operationlog> tbl_operationlog { get; set; }
        public virtual DbSet<tbl_policyDetail> tbl_policyDetail { get; set; }
        public virtual DbSet<tbl_policyWithEmployee> tbl_policyWithEmployee { get; set; }
        public virtual DbSet<tbl_realtime_enroll_data> tbl_realtime_enroll_data { get; set; }
        public virtual DbSet<tbl_realtime_userinfo> tbl_realtime_userinfo { get; set; }
        public virtual DbSet<tbl_setting> tbl_setting { get; set; }
        public virtual DbSet<tbl_temptable> tbl_temptable { get; set; }
        public virtual DbSet<tbl_timezone> tbl_timezone { get; set; }
        public virtual DbSet<tbl_workcode> tbl_workcode { get; set; }
        public virtual DbSet<tbl_workHourPolicy> tbl_workHourPolicy { get; set; }
        public virtual DbSet<tbl_fkcmd_trans_cmd_result_log_data> tbl_fkcmd_trans_cmd_result_log_data { get; set; }
        public virtual DbSet<tbl_fkcmd_trans_cmd_result_slog_data> tbl_fkcmd_trans_cmd_result_slog_data { get; set; }
        public virtual DbSet<tbl_realtime_doorstatus> tbl_realtime_doorstatus { get; set; }
        public virtual DbSet<tbl_realtime_glog> tbl_realtime_glog { get; set; }
    
        public virtual int usp_check_reset_fk_cmd(string dev_id, ObjectParameter trans_id)
        {
            var dev_idParameter = dev_id != null ?
                new ObjectParameter("dev_id", dev_id) :
                new ObjectParameter("dev_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_check_reset_fk_cmd", dev_idParameter, trans_id);
        }
    
        public virtual int usp_receive_cmd(string dev_id, ObjectParameter trans_id, ObjectParameter cmd_code, ObjectParameter cmd_param_bin)
        {
            var dev_idParameter = dev_id != null ?
                new ObjectParameter("dev_id", dev_id) :
                new ObjectParameter("dev_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_receive_cmd", dev_idParameter, trans_id, cmd_code, cmd_param_bin);
        }
    
        public virtual ObjectResult<string> usp_set_cmd_result(string dev_id, string trans_id, string return_code, byte[] cmd_result_bin)
        {
            var dev_idParameter = dev_id != null ?
                new ObjectParameter("dev_id", dev_id) :
                new ObjectParameter("dev_id", typeof(string));
    
            var trans_idParameter = trans_id != null ?
                new ObjectParameter("trans_id", trans_id) :
                new ObjectParameter("trans_id", typeof(string));
    
            var return_codeParameter = return_code != null ?
                new ObjectParameter("return_code", return_code) :
                new ObjectParameter("return_code", typeof(string));
    
            var cmd_result_binParameter = cmd_result_bin != null ?
                new ObjectParameter("cmd_result_bin", cmd_result_bin) :
                new ObjectParameter("cmd_result_bin", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_set_cmd_result", dev_idParameter, trans_idParameter, return_codeParameter, cmd_result_binParameter);
        }
    
        public virtual int usp_update_device_conn_status(string dev_id, string dev_name, Nullable<System.DateTime> tm_last_update, Nullable<System.DateTime> fktm_last_update, string dev_info, string dev_model)
        {
            var dev_idParameter = dev_id != null ?
                new ObjectParameter("dev_id", dev_id) :
                new ObjectParameter("dev_id", typeof(string));
    
            var dev_nameParameter = dev_name != null ?
                new ObjectParameter("dev_name", dev_name) :
                new ObjectParameter("dev_name", typeof(string));
    
            var tm_last_updateParameter = tm_last_update.HasValue ?
                new ObjectParameter("tm_last_update", tm_last_update) :
                new ObjectParameter("tm_last_update", typeof(System.DateTime));
    
            var fktm_last_updateParameter = fktm_last_update.HasValue ?
                new ObjectParameter("fktm_last_update", fktm_last_update) :
                new ObjectParameter("fktm_last_update", typeof(System.DateTime));
    
            var dev_infoParameter = dev_info != null ?
                new ObjectParameter("dev_info", dev_info) :
                new ObjectParameter("dev_info", typeof(string));
    
            var dev_modelParameter = dev_model != null ?
                new ObjectParameter("dev_model", dev_model) :
                new ObjectParameter("dev_model", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_update_device_conn_status", dev_idParameter, dev_nameParameter, tm_last_updateParameter, fktm_last_updateParameter, dev_infoParameter, dev_modelParameter);
        }
    }
}
