//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EagleEye.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_attendence
    {
        public int Code { get; set; }
        public Nullable<System.DateTime> Attendance_DateTime { get; set; }
        public string Attendance_Photo { get; set; }
        public Nullable<System.DateTime> Polling_DateTime { get; set; }
        public string Device_ID { get; set; }
        public string Employee_ID { get; set; }
        public string Employee_Name { get; set; }
        public string Status { get; set; }
        public string Status_Description { get; set; }
        public string WorkCode { get; set; }
        public string WorkCode_Description { get; set; }
        public string DoorStatus { get; set; }
        public string Verify_Mode { get; set; }
        public Nullable<bool> Status_TIS { get; set; }
        public Nullable<bool> Status_Oracle { get; set; }
        public Nullable<bool> Status_SQL { get; set; }
        public string Ext_Status { get; set; }
        public Nullable<bool> Status_MySQL { get; set; }
    }
}
