//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EagleEye.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_policyWithEmployee
    {
        public int Code { get; set; }
        public string Emp_id { get; set; }
        public Nullable<System.DateTime> Dt { get; set; }
        public string Workhour { get; set; }
        public string Overtime { get; set; }
        public string Breakhour { get; set; }
        public string Extrahour { get; set; }
        public string Policycode { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
