//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EagleEye.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_realtime_userinfo
    {
        public string user_id { get; set; }
        public string user_name { get; set; }
        public string privilige { get; set; }
        public string card { get; set; }
        public string Password { get; set; }
        public byte[] Face { get; set; }
        public byte[] photo { get; set; }
        public byte[] Fp_0 { get; set; }
        public byte[] Fp_1 { get; set; }
        public byte[] Fp_2 { get; set; }
        public byte[] Fp_3 { get; set; }
        public byte[] Fp_4 { get; set; }
        public byte[] Fp_5 { get; set; }
        public byte[] Fp_6 { get; set; }
        public byte[] Fp_7 { get; set; }
        public byte[] Fp_8 { get; set; }
        public byte[] Fp_9 { get; set; }
    }
}
