//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EagleEye.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_account
    {
        public int Code { get; set; }
        public string UserName { get; set; }
        public string Hash { get; set; }
        public byte[] Salt { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string Location { get; set; }
    }
}
