//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EagleEye.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_fkcmd_trans_offline
    {
        public string trans_id { get; set; }
        public string device_id { get; set; }
        public string user_id { get; set; }
        public string timezone_no { get; set; }
        public string cmd_code { get; set; }
        public string return_code { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
    }
}
