//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EagleEye.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_fkdevice_status
    {
        public string device_id { get; set; }
        public string device_name { get; set; }
        public int connected { get; set; }
        public System.DateTime last_update_time { get; set; }
        public Nullable<System.DateTime> last_update_fk_time { get; set; }
        public string device_info { get; set; }
        public string dev_model { get; set; }
        public string dev_status_info { get; set; }
        public Nullable<int> con_status { get; set; }
    }
}
