//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EagleEye.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_timezone
    {
        public int Code { get; set; }
        public string Timezone_No { get; set; }
        public string Timezone_Name { get; set; }
        public string Period_1_Start { get; set; }
        public string Period_1_End { get; set; }
        public string Period_2_Start { get; set; }
        public string Period_2_End { get; set; }
        public string Period_3_Start { get; set; }
        public string Period_3_End { get; set; }
        public string Period_4_Start { get; set; }
        public string Period_4_End { get; set; }
        public string Period_5_Start { get; set; }
        public string Period_5_End { get; set; }
        public string Period_6_Start { get; set; }
        public string Period_6_End { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
