//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EagleEye.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_menurights
    {
        public int Menu_Rights_Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<int> Menu_Id { get; set; }
        public Nullable<bool> Insert { get; set; }
        public Nullable<bool> Update { get; set; }
        public Nullable<bool> Delete { get; set; }
        public Nullable<bool> View { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
