//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EagleEye.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_communication
    {
        public int Code { get; set; }
        public string Server_IP { get; set; }
        public string SignalR_Port { get; set; }
        public string Server_Port { get; set; }
    }
}
