//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EagleEye.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_realtime_glog
    {
        public System.DateTime update_time { get; set; }
        public string device_id { get; set; }
        public string user_id { get; set; }
        public string verify_mode { get; set; }
        public string io_mode { get; set; }
        public Nullable<System.DateTime> io_time { get; set; }
        public string io_workcode { get; set; }
        public byte[] log_image { get; set; }
    }
}
