//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EagleEye.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_policyDetail
    {
        public int Code { get; set; }
        public Nullable<bool> DayCheck { get; set; }
        public string Day { get; set; }
        public string Workhour { get; set; }
        public string Overtime { get; set; }
        public string Breakhour { get; set; }
        public Nullable<bool> isOvertimeActive { get; set; }
        public Nullable<int> PolicyCode { get; set; }
    }
}
