//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hmsEntitiestest : DbContext
    {
        public hmsEntitiestest()
            : base("name=hmsEntitiestest")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<attendance> attendances { get; set; }
        public virtual DbSet<awaitingdevice> awaitingdevices { get; set; }
        public virtual DbSet<communication> communications { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<device> devices { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<exceptionlog> exceptionlogs { get; set; }
        public virtual DbSet<location> locations { get; set; }
        public virtual DbSet<manager> managers { get; set; }
        public virtual DbSet<menu> menus { get; set; }
        public virtual DbSet<menuright> menurights { get; set; }
        public virtual DbSet<setting> settings { get; set; }
        public virtual DbSet<wandevicedetail> wandevicedetails { get; set; }
    }
}
